import { z } from "zod";

import { Tool } from "./base";
import type { ToolResult, ToolContext } from "./base";

const KeepSilenceSchema = z
  .object({
    think: z
      .string()
      .min(1)
      .describe("你的内心独白，反映你最真实的内心想法，仅你自己可见"),
  })
  .strict();

/** Structured reply payload generated by the tool and delivered to the client. */
export type KeepSilence = z.infer<typeof KeepSilenceSchema>;

const KEEP_SILENCE_TOOL_DESCRIPTION = `
此工具用于保持沉默，即不向外界发送任何消息。可以填写内心独白来表达自己的想法，但不发送任何文本消息。
调用此工具后不应再调用任何工具，包括此工具本身，并结束当前对话轮次。
`;

export class KeepSilenceTool extends Tool {
  /** Returns the unique tool name. */
  name = "keep_silence";

  /** Returns the tool purpose and usage guidance. */
  description = KEEP_SILENCE_TOOL_DESCRIPTION;

  /** Returns the JSON Schema specifying the expected arguments. */
  parameters = KeepSilenceSchema.toJSONSchema();

  /**
   * Validates and emits a structured reply payload.
   * @param args - Tool arguments matching the reply schema.
   * @param context - Optional tool context (unused).
   */
  async execute(args: unknown, context?: ToolContext): Promise<ToolResult> {
    try {
      const payload = KeepSilenceSchema.parse(args);
      return {
        success: true,
        content:
          "你选择沉默，请不要再调用任何工具了，包括这个工具本身，直接结束当前对话轮次即可。",
      };
    } catch (err) {
      return {
        success: false,
        content: `Invalid structured reply: ${(err as Error).message}`,
      };
    }
  }
}
